#!/bin/bash

# Compute Pi Installation Script
# This script sets up the calendar server and sync service for automatic startup

set -e

echo "=== ECAL Compute Pi Installation Script ==="
echo "This will install:"
echo "  - Calendar Server (web application with /image endpoint for screenshots)"
echo "  - Calendar Sync Service (polls server for changes and uploads to Display Pi)"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "Please run this script with sudo"
    exit 1
fi

# Get the project root directory (parent of scripts directory)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
echo "Script directory: $SCRIPT_DIR"
echo "Project directory: $PROJECT_DIR"

# Get the current user
CURRENT_USER=$(whoami)
echo "Current user: $CURRENT_USER"

# Check if virtual environment exists
if [ ! -d "$PROJECT_DIR/venv" ]; then
    echo "Warning: Virtual environment not found at $PROJECT_DIR/venv"
    echo "Please create it first with:"
    echo "  cd $PROJECT_DIR"
    echo "  python3 -m venv venv"
    echo "  source venv/bin/activate"
    echo "  pip install -r requirements.txt"
    echo ""
    read -p "Continue anyway? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Installation cancelled."
        exit 1
    fi
fi

# Prompt for configuration
echo ""
echo "=== Calendar Sync Configuration ==="
echo ""
read -p "Display Pi IP address or hostname [raspberrypi.local]: " DISPLAY_PI_HOST
DISPLAY_PI_HOST=${DISPLAY_PI_HOST:-raspberrypi.local}

read -p "Display Pi port [8000]: " DISPLAY_PI_PORT
DISPLAY_PI_PORT=${DISPLAY_PI_PORT:-8000}

read -p "Calendar server port [5000]: " CALENDAR_PORT
CALENDAR_PORT=${CALENDAR_PORT:-5000}

# Calendar sync service always polls every 5 seconds
POLL_INTERVAL=5
MODE_ARGS=""
MODE_DESC="Continuous polling (checks for changes every 5 seconds)"

CALENDAR_URL="http://localhost:$CALENDAR_PORT"
ENDPOINT_URL="http://$DISPLAY_PI_HOST:$DISPLAY_PI_PORT/upload"

echo ""
echo "Configuration Summary:"
echo "  Calendar URL: $CALENDAR_URL"
echo "  Display Endpoint: $ENDPOINT_URL"
echo "  Update Mode: $MODE_DESC"
echo ""

# Install system dependencies
echo "Installing system dependencies..."
apt update
apt install -y chromium-browser
echo "Note: Chromium is used by calendar_server.py for rendering screenshots"

# Create log directory
mkdir -p /var/log/ecal
chown $CURRENT_USER:$CURRENT_USER /var/log/ecal

# Create calendar sync configuration file
cat > "$PROJECT_DIR/calendar_sync_config.env" << EOF
# Calendar Sync Service Configuration
# Generated by install_compute_pi.sh

CALENDAR_URL=$CALENDAR_URL
ENDPOINT_URL=$ENDPOINT_URL
MODE_ARGS=$MODE_ARGS
EOF

chown $CURRENT_USER:$CURRENT_USER "$PROJECT_DIR/calendar_sync_config.env"
echo "Created calendar sync configuration file"

# Create calendar server systemd service file
cat > /etc/systemd/system/ecal-calendar-server.service << EOF
[Unit]
Description=ECAL Calendar Server
After=network.target
Wants=network.target

[Service]
Type=simple
User=$CURRENT_USER
WorkingDirectory=$PROJECT_DIR
Environment=PATH=$PROJECT_DIR/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Environment=PYTHONPATH=$PROJECT_DIR
ExecStart=$PROJECT_DIR/venv/bin/python3 $PROJECT_DIR/calendar_server.py
Restart=always
RestartSec=10
StandardOutput=append:/var/log/ecal/calendar-server.log
StandardError=append:/var/log/ecal/calendar-server.log

[Install]
WantedBy=multi-user.target
EOF

# Create calendar sync service systemd service file
cat > /etc/systemd/system/ecal-calendar-sync.service << EOF
[Unit]
Description=ECAL Calendar Sync Service
After=ecal-calendar-server.service network-online.target
Wants=ecal-calendar-server.service network-online.target

[Service]
Type=simple
User=$CURRENT_USER
WorkingDirectory=$PROJECT_DIR
Environment=PATH=$PROJECT_DIR/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Environment=PYTHONPATH=$PROJECT_DIR
ExecStart=$PROJECT_DIR/venv/bin/python3 $PROJECT_DIR/calendar_sync_service.py --calendar-url $CALENDAR_URL --endpoint-url $ENDPOINT_URL
Restart=always
RestartSec=30
StandardOutput=append:/var/log/ecal/calendar-sync.log
StandardError=append:/var/log/ecal/calendar-sync.log

[Install]
WantedBy=multi-user.target
EOF

echo "Created systemd service files"

# Set proper permissions
chmod 644 /etc/systemd/system/ecal-calendar-server.service
chmod 644 /etc/systemd/system/ecal-calendar-sync.service

# Reload systemd
systemctl daemon-reload

# Enable the services
systemctl enable ecal-calendar-server.service
systemctl enable ecal-calendar-sync.service

echo ""
echo "=== Installation Complete ==="
echo ""
echo "Services installed:"
echo "  - ecal-calendar-server (Calendar web server)"
echo "  - ecal-calendar-sync (Calendar sync service)"
echo "Status: Enabled (will start on boot)"
echo ""
echo "Configuration:"
echo "  Calendar URL: $CALENDAR_URL"
echo "  Display Endpoint: $ENDPOINT_URL"
echo "  Update Mode: $MODE_DESC"
echo "  Config file: $PROJECT_DIR/calendar_sync_config.env"
echo ""
echo "=== Service Management ==="
echo "To start the services now:"
echo "  sudo systemctl start ecal-calendar-server"
echo "  sudo systemctl start ecal-calendar-sync"
echo ""
echo "To check status:"
echo "  sudo systemctl status ecal-calendar-server"
echo "  sudo systemctl status ecal-calendar-sync"
echo ""
echo "To view logs:"
echo "  sudo journalctl -u ecal-calendar-server -f"
echo "  sudo journalctl -u ecal-calendar-sync -f"
echo "  tail -f /var/log/ecal/calendar-server.log"
echo "  tail -f /var/log/ecal/calendar-sync.log"
echo ""
echo "=== Important Notes ==="
echo "1. Make sure your virtual environment is set up with:"
echo "     python3 -m venv venv"
echo "     source venv/bin/activate"
echo "     pip install -r requirements.txt"
echo ""
echo "2. Ensure you have:"
echo "     - service-account-key.json for Google Calendar access"
echo "     - Display Pi running in image_receiver mode"
echo "     - Display Pi accessible at: $ENDPOINT_URL"
echo ""
echo "3. Test connectivity to Display Pi:"
echo "     curl $ENDPOINT_URL"
echo ""
echo "4. To reconfigure calendar sync settings:"
echo "     Edit: $PROJECT_DIR/calendar_sync_config.env"
echo "     Then: sudo systemctl restart ecal-calendar-sync"
echo ""
echo "For more information, see:"
echo "  - ARCHITECTURE.md (system architecture)"
echo "  - QUICK_START.md (quick setup guide)"
echo "  - scripts/README.md (installation details)" 